spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf8
    username:          # MySQL ??? ? ?? ??
    password:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher   # ★ 레거시 방식 적용

mybatis:
  mapper-locations: classpath:mapper/**/*.xml # Mapper XML 파일의 위치를 지정합니다. (resources/mapper 폴더 생성 필요)
  type-aliases-package: spboard.board.Domain.entity # 결과 객체(Entity/DTO)의 패키지 경로를 지정하여 XML에서 짧은 이름을 쓸 수 있게 합니다.
  configuration:
    map-underscore-to-camel-case: true # 카멜 케이스(DB: user_id -> Java: userId) 자동 매핑 활성화
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
# ?? ?? ?? ?? ? ?? ??
server:
  port: 8084
  servlet:
    encoding:
      force-response: true

# S3 ??
cloud:
  aws:
    s3:
      bucket:
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false